/* This Frame was created with Netbeans v7.0.1 */
package graphics;

import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

/**
 *
 * @author ifw10239
 */
public class MainFrame extends javax.swing.JFrame {
	
	private int defaultFrameW = 1024;
	private int defaultFrameH = 768;
	
    /** Creates new form MainFrame */
    public MainFrame() {
        setUndecorated(true);
        
        initComponents();        
        
        setFullScreen(true);
        //validate();
        mainCanvas.paint(mainCanvas.getGraphics());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        mainCanvas = new Playground(defaultFrameW, defaultFrameH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainCanvas.setBackground(new java.awt.Color(0, 0, 0));
        mainCanvas.setForeground(new java.awt.Color(255, 255, 255));
        mainCanvas.setName("mainCanvas");
        
        mainCanvas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainCanvasKeyPressed(evt);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCanvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCanvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration
    private java.awt.Canvas mainCanvas;
    
    private void setFullScreen(boolean bool) {
    	DisplayMode dm = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode();
		defaultFrameW = dm.getWidth();
    	defaultFrameH = dm.getHeight();
    	
    	mainCanvas.setSize(defaultFrameW, defaultFrameH);
    	
    	GraphicsDevice graphicsDevice = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    	if(graphicsDevice.isFullScreenSupported()) {
    		if(bool)
    			graphicsDevice.setFullScreenWindow(this);
    		else
    			graphicsDevice.setFullScreenWindow(null);
    	}
    }
    private void mainCanvasKeyPressed(java.awt.event.KeyEvent evt) {
    	if(evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
    		dispose();
    		setFullScreen(false);
    		setUndecorated(false);
    		setVisible(true);
    	}
    }
}
